# LISTA 10 -  LIBRERÍA NUMPY

## <ins>Ejercicios Obligatorios </ins>

## EJERCICIO 1

In [9]:
import numpy as np
d1 = np.arange(9)
print(f"Dimensiones de d1 es {d1.ndim}")
print(f"Forma de d1 es {d1.shape}")
print(d1)
d3 = np.reshape(d1,(3,3,1))
print(f"Dimensiones de d1 es {d3.ndim}")
print(f"Forma de d1 es {d3.shape}")
print(d3)


Dimensiones de d1 es 1
Forma de d1 es (9,)
[0 1 2 3 4 5 6 7 8]
Dimensiones de d1 es 3
Forma de d1 es (3, 3, 1)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]


Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la shape antes y después del reshape.

## EJERCICIO 2

In [14]:
import numpy as np
d2a = np.array([[-6, 5], [-4, 3], [-2, 1]])
d2b = np.array([[1, 2], [3, 4], [5, 6]])
d2ab = np.concatenate((d2b,d2a), axis=1)
print(d2ab)

[[ 1  2 -6  5]
 [ 3  4 -4  3]
 [ 5  6 -2  1]]


Dados los arrays 2D ```[[-6, 5], [-4, 3], [-2, 1]] y [[1, 2], [3, 4], [5, 6]]```, concaténalos de modo que obtengas el array ```[[1, 2, -6, -5], [3, 4, -4, -3], [5, 6, -2, -1]]```

## EJERCICIO 3

In [19]:
import numpy as np
d2 = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]])
def isPal(word):
    return word == word[::-1]

pal = np.array([[isPal(word) for word in row] for row in d2]) # Genera un numpy array donde el resultado es el return de isPal(word) por cada word en row de cada row en d2
print(d2[pal]) # Hace una referencia cruzada con la matriz pal que está llena de [True, False, False]...

['ala' 'kayak' 'elle']


Dado el array 2D ```[["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]]```, busca las palabras que sean palíndromos. Necesitarás una función universal.

## EJERCICIO 4

In [5]:
import random
import numpy
number = random.randint(1,10)
attempt = -1
tries = []
while attempt != number:
    attempt = int(input("Intenta acertar el numero: "))
    tries.append(attempt)
    if attempt != number:
        print("Has fallado, prueba otra vez")
    else:
        print(f"Enhorabuena, el numero era {number} y te ha costado {len(tries)} intentos")
print(f"Tus intentos han sido: {tries}")

Has fallado, prueba otra vez
Has fallado, prueba otra vez
Enhorabuena, el numero era 3 y te ha costado 3 intentos
Tus intentos han sido: [1, 2, 3]


Crea un minijuego que piense un número aleatorio entre 1 y 10 y, hasta que no lo aciertes, te pida un número del 1 al 10. Cuando aciertes, tendrá que devolver el número de intentos y la frase: “¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}”. En caso de que falles, el juego deberá mostrar la frase “¡Has fallado! ¡Prueba otra vez!”

## EJERCICIO 5

Crea un minijuego que piense un array 1D aleatorio de 5 elementos. Los elementos serán números enteros entre 1 y 20. Para cada intento, primero tendrá que pedir 5 números enteros del 1 al 20. El juego nos tendrá que decir cuántos números del array hemos acertado y cuántos números del array están bien colocados. El juego no termina hasta que no se hayan acertado todos los números pensados en la posición correspondiente. Al acabar, se tendrá que mostrar la frase: “¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {}”

## EJERCICIO 6

A partir de la lista ```[-3, -2, -1, 0, 1, 2, 3]```, genera dos arrays aleatorios 2D de size = (3, 4) y súmalos.

## <ins>Ejercicios Opcionales </ins>

## EJERCICIO 7

Dado el array 2D ```[[1, 2, 3],[-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]]``` divídelo en 3 arrays 2D.

## EJERCICIO 8

Crea una función universal que dado un array de strings devuelva el número total de vocales de cada string.